#!/usr/bin/env python3
"""
Memento Failure Handler
Automatically creates GitHub issues when Memento breaks
"""

import os
import sys
from datetime import datetime
from pathlib import Path

GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN', '')  # Must be set in environment
REPO = "rollersrights/memento"

def create_github_issue(title, body, labels=None):
    """Create GitHub issue via API."""
    import urllib.request
    import json
    
    url = f"https://api.github.com/repos/{REPO}/issues"
    
    data = {
        "title": title,
        "body": body,
        "labels": labels or ["bug", "memory-system"]
    }
    
    req = urllib.request.Request(
        url,
        data=json.dumps(data).encode(),
        headers={
            "Authorization": f"token {GITHUB_TOKEN}",
            "Accept": "application/vnd.github.v3+json",
            "Content-Type": "application/json"
        },
        method="POST"
    )
    
    try:
        with urllib.request.urlopen(req) as response:
            result = json.loads(response.read().decode())
            return result.get('number'), result.get('html_url')
    except Exception as e:
        print(f"Failed to create issue: {e}")
        return None, None

def handle_memento_failure(error_type, error_msg, traceback=None):
    """Handle Memento failure - rollback + create issue."""
    
    timestamp = datetime.now().isoformat()
    
    # Title
    title = f"🚨 Memento Failure: {error_type} at {timestamp[:16]}"
    
    # Body
    body = f"""## Automatic Failure Report

**Time:** {timestamp}
**Type:** {error_type}
**Error:** {error_msg}

### Impact
Memento memory system is not functioning. Automatic rollback attempted.

### Logs
```
{traceback or 'No traceback available'}
```

### Checklist
- [ ] Investigate root cause
- [ ] Verify rollback succeeded
- [ ] Test memory operations
- [ ] Deploy fix
- [ ] Create backup of fixed state

### System Info
- Host: rita
- User: admin
- DB Location: `~/.openclaw/memory/memory.db`
- Auto-generated by: `memento_health.sh`

---
*This issue was automatically created by the Memento failure handler.*
"""
    
    # Create issue
    issue_num, issue_url = create_github_issue(title, body, ["bug", "critical", "memory-system"])
    
    if issue_num:
        print(f"✅ GitHub Issue #{issue_num} created: {issue_url}")
        
        # Also log locally
        log_file = Path.home() / ".openclaw/memory/failures.log"
        with open(log_file, 'a') as f:
            f.write(f"[{timestamp}] Issue #{issue_num}: {error_type}\n")
        
        return issue_num, issue_url
    else:
        print("❌ Failed to create GitHub issue")
        return None, None

if __name__ == "__main__":
    if len(sys.argv) > 1:
        error_type = sys.argv[1]
        error_msg = sys.argv[2] if len(sys.argv) > 2 else "Unknown error"
        handle_memento_failure(error_type, error_msg)
    else:
        print("Usage: memento_failure_handler.py <error_type> <error_msg>")
